### ISSUE TITLE
Create Cost service

### ISSUE THREAD

**Issue by SFrancis-cpu** [SFrancis-cpu/saltBookingManagementApp#113]
8 - Domain Driven Design - Service
Your next practical assignment is the service. Service is another building block of Domain Driven Design.

Building on the your group projects,

Group Lead Tasks:

Create a service package under your root package.
Create the main generic service interface called IService (with the create, read, update and delete methods) in the root of the service package.
Create a service interface with its implementation (in the impl package) for an entity. Use TDD.
Update your repository on GITHUB with the new code.
Create a Milestone with due date: September 08 2020, and title: Service Milestone.
Create issues (creation of service interface and implementation classes) and assign them to all group members, also add the issues to the Service Milestone. Each group member must be responsible for at least one entity.
Merge correct, error-free pull requests from group members.
Group Members Tasks:

Get the updated GITHUB repository from your group lead.
Solve the issue assigned to you by your group lead. Use TDD.
Make sure your service interface and its corresponding implementation are in the right packages.
Send (using pull request) your code to the group lead.
As soon as the group lead has updated the service, get the updated version.
All group members must submit their copy (origin) of the GITHUB repository. That is the repository on your GITHUB account, which must be in sync with your group lead's GITHUB repository.

**Comment by JunadeF** [comment]
Completed the task.
